/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Desk.glb 
Author: viettuansvn (https://sketchfab.com/viettuansvn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-hacked-pc-sketchfabweeklychallenge-825375cdf52142b79fb7af78d933e885
Title: Stylized-hacked-pc-sketchfabweeklychallenge
*/

import React, { useEffect, useMemo, useState } from "react";
import { useGLTF, TransformControls, OrbitControls } from "@react-three/drei";
import {
  Color,
  DebugLayerMaterial,
  Depth,
  Fresnel,
  LayerMaterial,
} from "lamina";
import * as LAYERS from "lamina";
import { button, useControls } from "leva";
import * as THREE from "three";
import { useFrame, useThree } from "@react-three/fiber";
import { motion } from "framer-motion";
import { animate, useMotionValue } from "framer-motion";

export function Desk(props) {
  const { inView } = props;
  const { nodes, materials } = useGLTF("/portfolio/models/Desk.glb");

  const group = React.useRef();
  const count = React.useRef(0);

  const { rotation, position, scale } = useControls("Desk", {
    rotation: {
      x: 0.2,
      y: 0.5,
      z: 0,
    },
    position: {
      x: 0,
      y: -1.8,
      z: 0,
    },
    scale: 30,
    Add: button((get) => {
      console.clear();
      const rotation = get("Desk.rotation");
      const position = get("Desk.position");
      const scale = get("Desk.scale");
      console.log({
        rotation,
        position,
        scale,
      });
    }),
  });

  useFrame((state) => {
    if (!group?.current) return;

    if (inView) {
      group.current.rotation.y += 0.001; // Rotate around the y-axis
    }
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={[scale, scale, scale]}
      position={[position?.x, position?.y, position?.z]}
      rotation={[rotation?.x, rotation?.y, rotation?.z]}
    >
      <mesh
        geometry={nodes.Final_lambert1_0.geometry}
        material={materials.lambert1}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/portfolio/models/Desk.glb");
