/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Island.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import { Depth, LayerMaterial } from "lamina";

export function Island(props) {
  const { nodes, materials } = useGLTF("/portfolio/models/Island.glb");

  const position = useControls("Island Position", {
    value: {
      x: 0,
      y: 0.95,
      z: 0,
    },
  });
  const scale = useControls("Island Scale", { value: 0.2 });
  const rotation = useControls("Island Rotation", {
    value: {
      x: 0,
      // y: -Math.PI / 2,
      y: -1.57,
      z: -0.09,
    },
  });

  return (
    <group
      {...props}
      dispose={null}
      // name="Desk"
      position={[position.value.x, position.value.y, position.value.z]}
      rotation={[rotation.value.x, rotation.value.y, rotation.value.z]}
      scale={[scale.value, scale.value, scale.value]}
    >
      <mesh
        geometry={nodes.Cube003_Cube002.geometry}
        // material={materials["Material.006"]}
      >
        <LayerMaterial>
          <Depth
            colorA={"red"}
            colorB={"blue"}
            alpha={1}
            mode="normal"
            near={0}
            far={2}
            origin={[1, 1, 1]}
          />
        </LayerMaterial>
      </mesh>
    </group>
  );
}

useGLTF.preload("/portfolio/models/Island.glb");
