/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/MacBook.glb 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import * as THREE from "three";
import { useControls } from "leva";
import { motion } from "framer-motion-3d";
import { animate, useMotionValue } from "framer-motion";

export function MacBook(props) {
  const { inView } = props;
  // const [animation, setAnimation] = React.useState("");
  const { nodes, materials } = useGLTF("/portfolio/models/MacBook.glb");
  const { viewport, ...rest } = useThree();
  const group = useRef();

  const { position, rotation, scale } = useControls("MacBook", {
    position: {
      x: 0,
      y: -0.4,
      z: 0,
    },
    rotation: {
      x: 0.2,
      y: 0,
      z: 0,
    },
    scale: 0.9,
  });

  useFrame((state) => {
    if (!group?.current) return;

    if (inView) {
      group.current.rotation.y += 0.001; // Rotate around the y-axis
    }
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={[scale, scale, scale]}
      rotation={[rotation.x, rotation.y, rotation.z]}
      position={[position.x, position.y, position.z]}
    >
      <mesh
        geometry={nodes.mesh485226736.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.mesh485226736_1.geometry}
        material={materials.mat23}
      />
      <mesh
        geometry={nodes.mesh485226736_2.geometry}
        material={materials.mat17}
      />
      <mesh
        geometry={nodes.mesh485226736_3.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.mesh256948792.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.mesh256948792_1.geometry}
        material={materials.mat23}
      />
      <mesh
        geometry={nodes.mesh256948792_2.geometry}
        material={materials.mat17}
      />
      <mesh
        geometry={nodes.mesh256948792_3.geometry}
        material={materials.mat25}
      />
    </group>
  );
}

useGLTF.preload("/portfolio/models/MacBook.glb");
