/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/MacBook2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export function MacBook2(props) {
  const { nodes, materials } = useGLTF('/models/MacBook2.glb')
  console.log('materials:', materials);
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[21, -11, 0]} scale={51.809}>
          <mesh geometry={nodes.mesh485226736.geometry} material={nodes.mesh485226736.material} />
          <mesh geometry={nodes.mesh485226736_1.geometry} material={nodes.mesh485226736_1.material} />
          <mesh geometry={nodes.mesh485226736_2.geometry} material={nodes.mesh485226736_2.material} />
          <mesh geometry={nodes.mesh485226736_3.geometry} material={nodes.mesh485226736_3.material} />
          <mesh geometry={nodes['Screenshot_2023-09-14_at_113009_AMpng'].geometry} material={nodes['Screenshot_2023-09-14_at_113009_AMpng'].material} position={[2.813, -0.772, -27.845]} />
          <mesh geometry={nodes.mesh256948792.geometry} material={nodes.mesh256948792.material} />
          <mesh geometry={nodes.mesh256948792_1.geometry} material={nodes.mesh256948792_1.material} />
          <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0.028, 0.85, -0.656]} scale={0.019} />
          <mesh geometry={nodes.mesh256948792_2.geometry} material={nodes.mesh256948792_2.material} />
          <mesh geometry={nodes.mesh256948792_3.geometry} material={nodes.mesh256948792_3.material} />
        </group>
        <directionalLight intensity={0.7} decay={2} rotation={[-0.506, 0.629, 0.756]} />
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[9.414, 145.657, 143.51]} rotation={[-0.584, -0.019, -0.013]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/MacBook2.glb')
