/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/NewMacbook.glb 
Author: artemtem (https://sketchfab.com/artemtem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-macbook-pro-a1708-dd3649453a034348a31d5c947bcdb222
Title: Apple MacBook Pro A1708
*/

import React, { useEffect, useMemo, useState } from "react";
import { useGLTF, TransformControls, OrbitControls } from "@react-three/drei";
import {
  Color,
  DebugLayerMaterial,
  Depth,
  Fresnel,
  LayerMaterial,
} from "lamina";
import * as LAYERS from "lamina";
import { button, useControls } from "leva";
import * as THREE from "three";
import { useFrame, useThree } from "@react-three/fiber";
import { motion } from "framer-motion";
import { animate, useMotionValue } from "framer-motion";
import { framerMotionConfig } from "../config";

export function NewMacbook(props) {
  const { inView, inView2 } = props;
  const { nodes, materials } = useGLTF("/portfolio/models/NewMacbook.glb");

  const group = React.useRef();
  const zPos = useMotionValue(0);
  const opacity = useMotionValue(0);

  const { rotation, position, scale } = useControls("MAC", {
    rotation: {
      x: 0.25,
      y: 0,
      z: 0,
    },
    position: {
      x: 0,
      y: 0,
      z: 0,
    },
    scale: 1.5,
    Add: button((get) => {
      console.clear();
      const rotation = get("MAC.rotation");
      const position = get("MAC.position");
      const scale = get("MAC.scale");
      console.log({
        rotation,
        position,
        scale,
      });
    }),
  });

  useEffect(() => {
    // animate(zPos, inView2 ? 0 : 40, {
    //   // ...framerMotionConfig,
    //   type: "spring",
    //   mass: 5,
    //   stiffness: 400,
    //   damping: 50,
    //   restDelta: 0.0001,
    //   duration: 1.25,
    // });
    // animate(opacity, inView2 ? 1 : 0, {
    //   // ...framerMotionConfig,
    //   // type: "spring",
    //   // mass: 5,
    //   // stiffness: 400,
    //   // damping: 50,
    //   // restDelta: 0.0001,
    //   // duration: 1.25,
    // });
  }, [inView2]);

  useFrame((state) => {
    if (!group?.current) return;
    group.current.position.x = zPos.get();
    if (group.current.position.x >= 40) {
      group.current.rotation.y = 0;
    }

    if (inView) {
      group.current.rotation.y += 0.001; // Rotate around the y-axis
    }
    // for (let key in materials) {
    //   console.log(key, materials[key]);
    //   // materials[key].transparent = true;
    //   materials[key].opacity = opacity.get();
    // }
  });

  // for (let key in materials) {
  //   console.log(key, materials[key]);
  //   // materials[key].transparent = true;
  //   materials[key].opacity = 0;
  // }

  const material1 = new THREE.MeshStandardMaterial({
    // color: 0xffffff,
    color: "#000000",
    roughness: 0.1,
    metalness: 0.5,
    envMapIntensity: 10,
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={[scale, scale, scale]}
      position={[position?.x, position?.y, position?.z]}
      rotation={[rotation?.x, rotation?.y, rotation?.z]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            // material={material1}
            material={
              materials.apple_a1708_macbook_pro_13_mpxq2ua_space_gray_decol_mat
            }
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            // material={material1}
            material={
              materials.apple_a1708_macbook_pro_13_mpxq2ua_space_gray_decol_mat
            }
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            // material={material1}
            material={
              materials.apple_a1708_macbook_pro_13_mpxq2ua_space_gray_main_mat
            }
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            // material={material1}
            material={
              materials.apple_a1708_macbook_pro_13_mpxq2ua_space_gray_decol_mat
            }
          />
          <mesh
            geometry={nodes.defaultMaterial_4.geometry}
            // material={material1}
            material={
              materials.apple_a1708_macbook_pro_13_mpxq2ua_space_gray_main_mat
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/portfolio/models/NewMacbook.glb");
